package experiment;
import java.util.Scanner;
public class TestCircleWithException {
	public  static  void  main(String[]  args)  {
        Scanner  in  =  new  Scanner(System.in);
        int  radius  =  in.nextInt();
        
        
        
        
        
        
	}
}
	class  CircleWithException  {
        private  double  radius;

        public  CircleWithException(double  newRadius)  {
            setRadius(newRadius);
        }

        public  double  getRadius()  {
            return  radius;
        }

        public  void  setRadius(double  newRadius)
                throws  IllegalArgumentException  {
        	
        	
        	
        	
        	
        	
        }
        public  double  findArea()  {
            return  radius  *  radius  *  3.14159;
        }
}